"""
Model qatlami testlari:
  - __str__ ko'rinishi
  - slug avtomatik generatsiyasi va unikalligi
  - default qiymatlar
  - SiteSettings singleton (pk har doim 1)
"""
import pytest
from django.utils import timezone

from main import models as m

pytestmark = pytest.mark.django_db


# ── SiteSettings singleton ────────────────────────────────────────────────────
class TestSiteSettings:
    def test_get_creates_singleton(self):
        s = m.SiteSettings.get()
        assert s.pk == 1
        assert m.SiteSettings.objects.count() == 1

    def test_save_always_pk_1(self):
        m.SiteSettings.get()
        s2 = m.SiteSettings(site_name="Boshqa")
        s2.save()
        assert s2.pk == 1
        assert m.SiteSettings.objects.count() == 1  # ikkinchi obyekt yaratilmadi

    def test_defaults(self):
        s = m.SiteSettings.get()
        assert s.site_name == "TIIU"
        assert s.founded_year == 2015
        assert s.smtp_port == 587

    def test_str(self):
        s = m.SiteSettings.get()
        assert str(s) == s.site_name


# ── Slug generatsiya ──────────────────────────────────────────────────────────
class TestSlugGeneration:
    def test_faculty_slug_autogenerated(self):
        f = m.Faculty.objects.create(name="Axborot Texnologiyalari", description="d")
        assert f.slug == "axborot-texnologiyalari"

    def test_faculty_slug_unique_collision(self):
        m.Faculty.objects.create(name="Iqtisodiyot", description="d")
        f2 = m.Faculty.objects.create(name="Iqtisodiyot", description="d")
        assert f2.slug == "iqtisodiyot-1"
        f3 = m.Faculty.objects.create(name="Iqtisodiyot", description="d")
        assert f3.slug == "iqtisodiyot-2"

    def test_slug_not_overwritten_on_update(self):
        f = m.Faculty.objects.create(name="Boshlang'ich", description="d")
        original = f.slug
        f.name = "O'zgargan nom"
        f.save()
        assert f.slug == original  # slug bir marta o'rnatiladi

    def test_teacher_slug(self):
        t = m.Teacher.objects.create(full_name="Alisher Karimov")
        assert t.slug == "alisher-karimov"

    def test_news_slug_collision(self):
        img_a = _img()
        n1 = m.News.objects.create(title="Xabar", image=img_a, short_text="s", body="b")
        n2 = m.News.objects.create(title="Xabar", image=_img(), short_text="s", body="b")
        assert n1.slug == "xabar"
        assert n2.slug == "xabar-1"

    def test_journal_slug_pattern(self):
        j = m.JournalIssue.objects.create(title="1-son", year=2025, issue_number=3)
        assert j.slug == "2025-3-son"

    def test_dissertation_slug_uses_author_and_title(self):
        d = m.Dissertation.objects.create(author="Karimov A", title="Ta'lim tizimi tahlili")
        assert d.slug.startswith("karimov-a")


# ── __str__ ──────────────────────────────────────────────────────────────────
class TestStr:
    def test_faculty_str(self):
        f = m.Faculty.objects.create(name="Huquqshunoslik", description="d")
        assert str(f) == "Huquqshunoslik"

    def test_teacher_str_includes_position(self):
        t = m.Teacher.objects.create(full_name="N. Aliyev", position="Professor")
        assert str(t) == "N. Aliyev — Professor"

    def test_contact_message_str(self):
        cm = m.ContactMessage.objects.create(first_name="Ali", last_name="Vali")
        assert "Ali" in str(cm) and "Vali" in str(cm)

    def test_journal_str(self):
        j = m.JournalIssue.objects.create(title="son", year=2024, issue_number=2)
        assert str(j) == "2024-yil, 2-son"


# ── Default qiymatlar ─────────────────────────────────────────────────────────
class TestDefaults:
    def test_faculty_defaults(self):
        f = m.Faculty.objects.create(name="X", description="d")
        assert f.icon == "🎓"
        assert f.degree == "bachelor"
        assert f.duration == 4
        assert f.is_active is True

    def test_news_defaults(self):
        n = m.News.objects.create(title="T", image=_img(), short_text="s", body="b")
        assert n.views == 0
        assert n.is_active is True
        assert n.is_featured is False
        assert n.created_at is not None

    def test_contact_message_status_default(self):
        cm = m.ContactMessage.objects.create(first_name="A", last_name="B")
        assert cm.status == "new"

    def test_center_default_icon(self):
        c = m.Center.objects.create(name="Markaz")
        assert c.icon == "🏢"


# ── Ordering ──────────────────────────────────────────────────────────────────
class TestOrdering:
    def test_news_ordered_by_created_desc(self):
        n1 = m.News.objects.create(title="Birinchi", image=_img(), short_text="s", body="b")
        n2 = m.News.objects.create(title="Ikkinchi", image=_img(), short_text="s", body="b")
        ids = list(m.News.objects.values_list("id", flat=True))
        assert ids[0] == n2.id  # eng yangi birinchi

    def test_faculty_ordered_by_order(self):
        a = m.Faculty.objects.create(name="A", description="d", order=2)
        b = m.Faculty.objects.create(name="B", description="d", order=1)
        first = m.Faculty.objects.first()
        assert first.id == b.id


# ── helper ────────────────────────────────────────────────────────────────────
def _img():
    import io
    from PIL import Image
    from django.core.files.uploadedfile import SimpleUploadedFile
    buf = io.BytesIO()
    Image.new("RGB", (10, 10), (1, 2, 3)).save(buf, format="PNG")
    buf.seek(0)
    return SimpleUploadedFile("i.png", buf.read(), content_type="image/png")
