# Generated by Django 5.1.15 on 2026-04-16 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direction', models.CharField(blank=True, max_length=200, verbose_name="Qiziqtirgan yo'nalish")),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('read', "O'qilgan"), ('answered', 'Javob berilgan')], default='new', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Joyi')),
                ('event_date', models.DateTimeField(verbose_name='Tadbir sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Qisqa nomi / Badge')),
                ('icon', models.CharField(default='🎓', max_length=10, verbose_name='Emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faculties/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr')], default='bachelor', max_length=20, verbose_name='Daraja')),
                ('study_forms', models.CharField(blank=True, default='Kunduzgi, Kechki, Sirtqi', max_length=200, verbose_name="O'qish shakllari")),
                ('duration', models.PositiveIntegerField(default=4, verbose_name="O'qish muddati (yil)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'FAQ (Savol-javob)',
                'verbose_name_plural': 'FAQ (Savol-javoblar)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Album nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Muqova rasmi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Galereya albomi',
                'verbose_name_plural': 'Galereya albumlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#3b82f6', max_length=30, verbose_name='Rang')),
            ],
            options={
                'verbose_name': 'Yangilik kategoriyasi',
                'verbose_name_plural': 'Yangilik kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TIIU', max_length=200, verbose_name='Sayt nomi')),
                ('site_name_full', models.CharField(default='Toshkent ijtimoiy innovatsiya universiteti', max_length=300, verbose_name="To'liq nom")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Favicon')),
                ('address', models.TextField(default="Toshkent, Sergeli tumani, Uzumzor ko'chasi, 37", verbose_name='Manzil')),
                ('phone1', models.CharField(default='+998 78 113 17 17', max_length=30, verbose_name='Telefon 1')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='Telefon 2')),
                ('email', models.EmailField(default='info@tiiu.uz', max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(default='Du–Ju: 9:00–18:00 | Shanba: 9:00–14:00', max_length=200, verbose_name='Ish vaqti')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('founded_year', models.PositiveIntegerField(default=2015, verbose_name='Tashkil yili')),
                ('student_count', models.PositiveIntegerField(default=1200, verbose_name='Talabalar soni')),
                ('teacher_count', models.PositiveIntegerField(default=50, verbose_name="O'qituvchilar soni")),
                ('direction_count', models.PositiveIntegerField(default=9, verbose_name="Yo'nalishlar soni")),
                ('about_text', models.TextField(blank=True, verbose_name='Universitet haqida (qisqa)')),
                ('hero_title', models.CharField(default='Kelajakni bugun shakllantir', max_length=200, verbose_name='Hero sarlavha')),
                ('hero_subtitle', models.TextField(blank=True, default="Toshkent ijtimoiy innovatsiya universiteti — ilg'or ta'lim texnologiyalari asosida zamonaviy mutaxassislar tayyorlaydigan nodavlat oliy ta'lim muassasasi.", verbose_name='Hero izoh')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(blank=True, verbose_name='Izoh')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Rasm')),
                ('btn_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('btn_url', models.CharField(blank=True, default='/', max_length=200, verbose_name='Tugma URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.gallery', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Rasm')),
                ('short_text', models.TextField(max_length=500, verbose_name='Qisqa matn')),
                ('body', models.TextField(verbose_name="To'liq matn")),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Muallif')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy yangilik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='main.newscategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('position', models.CharField(choices=[('professor', 'Professor'), ('dotsent', 'Dotsent'), ('oqituvchi', "O'qituvchi"), ('assistant', 'Assistent')], default='oqituvchi', max_length=30, verbose_name='Lavozim')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Kafedra')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='main.faculty', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
