# Generated by Django 5.1.15 on 2026-04-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_center_leadership_department_teacher_kafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='qualification',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ilmiy daraja'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='rank',
            field=models.CharField(blank=True, help_text='Masalan: Rektor, Prorektor', max_length=100, verbose_name='Unvon (qisqa)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='reception_days',
            field=models.CharField(blank=True, help_text='Masalan: Seshanba, Payshanba, Juma', max_length=200, verbose_name='Qabul kunlari'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='reception_time',
            field=models.CharField(blank=True, help_text='Masalan: 15:00 – 16:00', max_length=100, verbose_name='Qabul vaqti'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='position',
            field=models.CharField(max_length=300, verbose_name="Lavozim (to'liq)"),
        ),
    ]
