# Generated by Django 5.1.15 on 2026-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_leadership_qualification_leadership_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='head_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='center',
            name='head_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='center',
            name='head_role',
            field=models.CharField(blank=True, max_length=300, verbose_name='Rahbar lavozimi'),
        ),
        migrations.AddField(
            model_name='center',
            name='work_hours',
            field=models.CharField(blank=True, help_text='Masalan: Dushanbidan Jumagacha 10:00–15:00', max_length=200, verbose_name='Ish vaqti'),
        ),
        migrations.AlterField(
            model_name='center',
            name='head',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rahbar ismi'),
        ),
        migrations.AlterField(
            model_name='center',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='centers/', verbose_name='Rasm (rahbar foto)'),
        ),
    ]
