# Generated by Django 5.1.15 on 2026-04-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_center_head_email_center_head_phone_center_head_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozim'),
        ),
    ]
