# Generated by Django 5.1.15 on 2026-04-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_teacher_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.event', verbose_name='Tadbir')),
            ],
            options={
                'verbose_name': 'Tadbir rasmi',
                'verbose_name_plural': 'Tadbir rasmlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari',
                'ordering': ['order'],
            },
        ),
    ]
