# Generated by Django 5.1.15 on 2026-04-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_eventimage_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, verbose_name="To'liq matn"),
        ),
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Qisqa tavsif'),
        ),
    ]
