# Generated by Django 5.1.15 on 2026-05-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_obsolete_static_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_badge',
            field=models.CharField(default='Missiya va Maqsad', max_length=100, verbose_name='Haqida belgisi (tag)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_2',
            field=models.TextField(blank=True, default="TIIU talaba-yoshlarga yuqori sifatli ta'lim xizmatlarini taklif etadi. Universitet mamlakatimizning yetakchi oliy ta'lim tashkiloti sifatida ijtimoiy-iqtisodiy sohadagi oʻzgarishlarga innovatsion yechimlar bilan hissa qoʻshishni maqsad qilib qoʻygan.", verbose_name='Universitet haqida (2-paragraf)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='Bilim orqali kelajakni bunyod etamiz', max_length=300, verbose_name='Haqida sarlavha'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, default="Toshkent ijtimoiy innovatsiya universiteti ilgʻor ta'lim texnologiyalariga asoslangan holda ijtimoiy soha va iqtisodiyot tarmoqlari uchun zamonaviy bilim va koʻnikmalarga ega, mustaqil fikrlaydigani malakali kadrlarni yetishtirib beruvchi nodavlat oliy ta'lim tashkiloti hisoblanadi.", verbose_name='Universitet haqida (1-paragraf)'),
        ),
    ]
