# Generated by Django 5.1.15 on 2026-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sitesettings_about_badge_sitesettings_about_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='Haqida rasm'),
        ),
    ]
