# Generated by Django 5.1.15 on 2026-05-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitesettings_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Parol (App Password)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Email (yuboruvchi)'),
        ),
    ]
